import requests
import time
import json
import traceback
from .base import BaseClient

url = "https://evaluators.librai.tech/api/v1/evaluator/single-run"

class LibrAI_Client(BaseClient):
    def __init__(
        self,
        api_key: str,
        max_requests_per_minute=200,
        request_window=60,
    ) -> None:
        super().__init__("", "", max_requests_per_minute, request_window)
        self.api_key = api_key

    def call_librai_evaluator(self, evaluator_name: str, mapped_data: dict):

        headers = {
            "Content-Type": "application/json",
            "Accept": "application/json",
            "Authorization": f"Bearer {self.api_key}",
        }

        placeholder_pairs = {key: key for key in mapped_data.keys()}

        payload = {
            "evaluator_name": f"{evaluator_name}",
            "placeholder_pairs": placeholder_pairs,
            "evaluator_data": mapped_data,
        }
        response = requests.post(url, headers=headers, data=json.dumps(payload))
        # print(response.text)
        return eval(response.text)["data"]

    def _call(self, mapped_data: dict, **kwargs):
        num_retries = kwargs.get("num_retries", 1)
        evaluator_name = kwargs.get("evaluator_name", None)
        post_check_function = kwargs.get("post_check_function", None)
        assert evaluator_name is not None

        r = ""
        for i in range(num_retries):
            try:
                r = self.call_librai_evaluator(evaluator_name, mapped_data)

                if post_check_function is None:
                    break
                else:
                    post_r = post_check_function(r)
                    if post_r:
                        return post_r
                    else:
                        print(f"Warning: Post check function failed. Response is {r} Retrying {i} ...")
            except Exception as e:
                # Possible error: name 'null' is not defined, Reason: No auth to call evaluator.
                print("Error in LibrAI Evaluator: ", e)
                print(traceback.format_exc())
                time.sleep(1)
        if r == "":
            print(f"LibrAI Evaluator Error, output is empty.")
        return r
